"Initial Q-Values Mean": 0
"Initial Q-Values Sigma": 0
"Operations Left": 100000
"Min Refresh Rate [ms]": 10
"Visualize Memory": true

"Show Every...": 1
"...Planning Update": true
"...Experience Update": true
"...Action Taken": true
"...Episode Finish": true
"...Episode Start": true

"Ice Floor": false
"X-Torus": false
"Y-Torus": false
"Reward Black": -1
"Reward Cyan": -10
"Reward Brown": -100
"Discount \u03B3": 1
"Learning Rate \u03B1": 0.1
"\u03B1 = 1/count((S,A))": false
"n-Step n": 1
"Dyna-Q n": 0
"On-Policy": true
"Update by Expectation": false
"Decay \u03B5 Episode-wise": false

"Exploration Rate \u03B5 (b)": 0.5
"\u03B5-Decay Rate (b)": 0.9999

"Exploration Rate \u03B5 (t)": 0
"\u03B5-Decay Rate (t)": 1

"world": null